name: Caller Workflow

on: workflow_dispatch

jobs:
  call-reusable:
    uses: ./.github/workflows/reuseable-ci.yml
    with:
      username: Sujal
    secrets:
      my_secret: ${{secrets.GITHUB_TOKEN}}
