name: CI CD Pipeline

on:
  push:
    branches:
      - master

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.build.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        id: build
        run: |
          TAG=${{ github.sha }}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/github-actions-learning:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/github-actions-learning:$TAG .

      - name: Push Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-learning:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-learning:${{ steps.build.outputs.tag }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/github-actions-learning:${{ needs.build-and-push.outputs.image_tag }}
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/github-actions-learning:${{ needs.build-and-push.outputs.image_tag }}
