name: My New Workspace

on: workflow_dispatch

env:
  MY_NAME: SUJAL

jobs:
    new_job:
      runs-on: ubuntu-latest
      env:
        JOB_SCOPE: JAMSANDEKAR
      steps:
        - name: Demo
          env:
            STEP_SCOPE: IRELAND
          run: echo "Hello ${MY_NAME} ${JOB_SCOPE}, ${STEP_SCOPE}"
