name: Matrix Demo

on: workflow_dispatch

jobs:
  matrix_job:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          version: [1,2,3]

      steps:
        - name: Print Versions
          run: echo "Running version ${{matrix.version}}"
