name: Run Tests

on:
  push:
    branches:
      - master
    pull-request:

job: 
  run_tests:
    runs-on: ubuntu-latest

    step:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest
